/**
 * scripts/make-stubs.ts — generate markdown stubs for newly-downloaded transcripts
 * and maintain the yt-dlp download archive.
 *
 * Scans data/transcripts/raw/ for *.info.json files produced by
 * `npm run fetch` (yt-dlp --write-info-json). For each one that does not
 * already have a matching markdown file in data/transcripts/content/,
 * writes a stub with known fields pre-filled and human-required fields
 * set to `null`.
 *
 * Also writes data/transcripts/archive.txt with `youtube <id>` entries
 * for every video info.json seen. yt-dlp's --download-archive doesn't
 * write when --skip-download is set, so we maintain it ourselves here.
 *
 * Review workflow: open the stub, replace each `null` with the correct
 * value, merge.
 *
 * Usage: npm run make-stubs
 */

import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const RAW_DIR = "data/transcripts/raw";
const CONTENT_DIR = "data/transcripts/content";
const ARCHIVE_PATH = "data/transcripts/archive.txt";

type YtDlpInfo = {
  id: string;
  title?: string;
  upload_date?: string; // YYYYMMDD for videos; absent for playlists
  duration?: number;
  _type?: string; // "playlist" for channel/playlist entries, undefined for videos
};

function formatUploadDate(yyyymmdd: string): string {
  return `${yyyymmdd.slice(0, 4)}-${yyyymmdd.slice(4, 6)}-${yyyymmdd.slice(6, 8)}`;
}

function secondsToHms(total: number): string {
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(h)}:${pad(m)}:${pad(s)}`;
}

function renderStub(info: YtDlpInfo, vttPath: string): string {
  if (!info.upload_date || !info.title || info.duration === undefined) {
    throw new Error(`Missing required fields on video ${info.id}`);
  }
  const date = formatUploadDate(info.upload_date);
  const safeTitle = info.title.replace(/"/g, '\\"');
  const durationHms = secondsToHms(info.duration);
  return `---
# Auto-generated by scripts/make-stubs.ts.
# Review the fields below, adjust as needed, and merge the PR.

content_id: sermon-${date}-${info.id}
youtube_id: ${info.id}
youtube_title: "${safeTitle}"
upload_date: ${date}
duration_seconds: ${info.duration}  # ${durationHms}
vtt_path: ${vttPath}

# Watch: https://www.youtube.com/watch?v=${info.id}

# --- REVIEW: confirm defaults or override ---
title: "${safeTitle}"          # cleaned-up display title; defaults to youtube_title
content_description: null      # short summary for the index; auto-filled by make-descriptions
speaker: "brett_tilford"       # "brett_tilford" or "guest:first-last"
content_type: "sermon"         # sermon | table_talk | guest_sermon | worship | story_sunday | panel_discussion | announcements
content_start: null            # when the content begins in the video, format "hh:mm:ss" (e.g. "00:28:15")
content_end: null              # when the content ends, format "hh:mm:ss"
series: null                   # leave null if not in a series

# --- defaults ok as-is ---
consent_status: granted
---
`;
}

async function main() {
  await mkdir(CONTENT_DIR, { recursive: true });

  const rawEntries = await readdir(RAW_DIR).catch(() => [] as string[]);
  const infoFiles = rawEntries.filter((f) => f.endsWith(".info.json"));

  if (infoFiles.length === 0) {
    console.log("No info.json files found — nothing to stub.");
    return;
  }

  let created = 0;
  let skippedExisting = 0;
  let skippedNonVideo = 0;
  let skippedMissingVtt = 0;
  const videoIds: string[] = [];

  for (const infoFile of infoFiles) {
    const base = infoFile.replace(/\.info\.json$/, "");
    const infoRaw = await readFile(join(RAW_DIR, infoFile), "utf8");
    const info: YtDlpInfo = JSON.parse(infoRaw);

    // Skip channel-level or playlist info.json (yt-dlp writes one when given
    // a channel URL). These have `_type: "playlist"` and no upload_date.
    if (info._type === "playlist" || !info.upload_date) {
      skippedNonVideo++;
      continue;
    }

    // Video was processed — record in archive so yt-dlp skips it on rerun,
    // whether or not we got a transcript.
    videoIds.push(info.id);

    const vttPath = `${RAW_DIR}/${base}.en.vtt`;
    if (!existsSync(vttPath)) {
      // No English auto-captions available for this video. Nothing to index.
      console.warn(`  skip ${info.id} — no VTT (no English captions on YouTube)`);
      skippedMissingVtt++;
      continue;
    }

    const stubPath = join(CONTENT_DIR, `${base}.md`);
    if (existsSync(stubPath)) {
      skippedExisting++;
      continue;
    }

    await writeFile(stubPath, renderStub(info, vttPath));
    created++;
  }

  // Maintain the download archive ourselves. yt-dlp doesn't write it when
  // --skip-download is set. Format: "youtube <id>" per line. Deduplicated
  // and sorted for stable diffs.
  const existingArchive = await readFile(ARCHIVE_PATH, "utf8").catch(() => "");
  const existingIds = new Set(
    existingArchive
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.startsWith("youtube "))
      .map((l) => l.slice("youtube ".length)),
  );
  for (const id of videoIds) existingIds.add(id);
  const sorted = [...existingIds].sort();
  const archiveBody = sorted.map((id) => `youtube ${id}`).join("\n") + "\n";
  await writeFile(ARCHIVE_PATH, archiveBody);

  console.log(
    `Stubs: created ${created}, skipped ${skippedExisting} existing, ` +
      `skipped ${skippedNonVideo} non-video, ` +
      `skipped ${skippedMissingVtt} missing VTT. ` +
      `Archive: ${sorted.length} total video IDs.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
